### ISSUE TITLE
这个是魔改过嘛

### ISSUE THREAD

**Issue by Zoe-Wh1t3zZ** [Yuri-YuzuChaN/setu#1]

**Comment by 3273576540** [comment]
好吧好像我没更新本体

**Comment by Yuri-YuzuChaN** [comment]
最近未更新过，把`new_logger`删了，然后新加一行`from hoshino.log import new_logger`

**Comment by Zoe-Wh1t3zZ** [comment]
好的谢谢！

**Comment by 3273576540** [comment]
File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\setu\__init__.py", line 1
    new_loggerfrom hoshino.log import new_logger
                   ^
SyntaxError: invalid syntax

**Comment by Zoe-Wh1t3zZ** [comment]
设置了后不会自动撤回

**Comment by Zoe-Wh1t3zZ** [comment]
> _未提供说明。_
