### ISSUE TITLE
依赖装了还是找不到依赖

### ISSUE THREAD

**Issue by Zoe-Wh1t3zZ** [Yuri-YuzuChaN/setu#2]
ModuleNotFoundError: No module named 'pixivpy_async'

**Comment by Zoe-Wh1t3zZ** [comment]
![image](https://user-images.githubusercontent.com/94744908/152684600-afe6a5ba-9a76-453b-92e8-01e0f50e28be.png)

**Comment by Yuri-YuzuChaN** [comment]
pip install pixivpy-async[socks]，我依赖写错了

**Comment by Zoe-Wh1t3zZ** [comment]
代理安装也试了还是找不到依赖
